# Generated by Django 4.2.7 on 2023-11-12 14:28

from django.db import migrations
import gameLogics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ships',
            name='mid',
        ),
        migrations.AlterField(
            model_name='ships',
            name='value',
            field=gameLogics.models.MoneyField(decimal_places=2, max_digits=100),
        ),
    ]
