# Generated by Django 4.2.7 on 2023-11-12 15:03

from django.db import migrations
import gameLogics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0003_alter_ships_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='callisto',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='deimos',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='earth',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='enceladus',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='europa',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='ganymede',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='io',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='mars',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='moon',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='phobos',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='titan',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='triton',
            field=gameLogics.models.YesNoBooleanField(),
        ),
    ]
