# Generated by Django 4.2.7 on 2023-11-12 15:05

from django.db import migrations, models
import gameLogics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0004_alter_commodities_callisto_alter_commodities_deimos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='callisto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='deimos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='earth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='edible',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='enceladus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='europa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='fragile',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='ganymede',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='io',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='mars',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='moon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='perishable',
            field=gameLogics.models.YesNoBooleanField(),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='phobos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='titan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commodities',
            name='triton',
            field=models.CharField(max_length=100),
        ),
    ]
