# Generated by Django 4.2.7 on 2023-11-12 15:14

from django.db import migrations
import gameLogics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0005_alter_commodities_callisto_alter_commodities_deimos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crews',
            name='weeklySalary',
            field=gameLogics.models.MoneyField(decimal_places=2, max_digits=100),
        ),
    ]
