# Generated by Django 4.2.7 on 2023-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLogics', '0006_alter_crews_weeklysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ships',
            name='mid',
            field=models.IntegerField(default=0),
        ),
    ]
